global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'caddy'
    metrics_path: /metrics
    static_configs:
      - targets: ['caddy:2019']
  - job_name: 'http-dummy-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['http-dummy-service:8080']
